### ISSUE TITLE
Add init container to purge Fastly cache on metacpan-web deployment starting

### ISSUE THREAD

**Issue by ssoriche** [metacpan/metacpan-k8s#45]
As per this comment: https://github.com/metacpan/metacpan-web/issues/3007#issuecomment-2033274148

Create an `init:` container in the [apps--web deployment](https://github.com/metacpan/metacpan-k8s/blob/main/apps/web/base/deployment.yaml) using a distro-less image with `curl` that can issue the call to Fastly.

The alternative that's available is to create an ArgoCD PostSync hook that runs a Kubernetes job that issues the `curl` command as documented in the ArgoCD documentation found here:

https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/

The ArgoCD PostSync is the preferred method as it is run after successful completion of the deployment.

**Comment by haarg** [comment]
If using curl, the purge request would look like:
```
curl -s -X POST \
  -H "Fastly-Key: <api_key>" \
  -H "Accept: application/json" \
  "https://api.fastly.com/service/<service_id>/purge/content_type=text/html"
```
Using the appropriate key and the service id for `metacpan.org`.
