### ISSUE TITLE
Web/API cronjobs

### ISSUE THREAD

**Issue by ranguard** [metacpan/metacpan-k8s#46]
https://github.com/metacpan/metacpan-k8s/blob/main/apps/grep/base/cronjob.yaml is an example of setting up a cron job...

Observations

### Which container is used for a cronjob...
```
          containers:
          - name: repo-refresh
            image: bitnami/git:latest
```

### QUESTION: Best practice - for many cron jobs...

We have many cronjobs e.g. for the API (https://github.com/metacpan/metacpan-puppet/blob/master/hieradata/common.yaml#L257) - would you setup a `cronjob_xxx.yaml` for each cron, or define `spec` multiple times somehow? - is there a public repo with examples of this?

**Comment by ssoriche** [comment]
Yeah, I'd create a separate `cronjob_xxx.yaml` for each cronjob. It's much easier to read, diff, and copy when they're in separate files.
