### ISSUE TITLE
Install rook.io in hz cluster

### ISSUE THREAD

**Issue by ssoriche** [metacpan/metacpan-k8s#54]
Following the pattern of other infrastructure applications, install rook.io manifests in the `platform/rook` directory for installation in the kubernetes clusters via ArgoCD (must define an `Application.yaml` using `apps/web/hz/prod_application.yaml` as an example).

The rook configuration should use the volume created and mounted in issue https://github.com/metacpan/metacpan-k8s/issues/53 as it's primary storage configuration

**Comment by ranguard** [comment]
Closing for https://github.com/metacpan/metacpan-k8s/issues/57 which is all storage steps
