### ISSUE TITLE
Update grep manifests to use Ceph filesystem storage

### ISSUE THREAD

**Issue by ssoriche** [metacpan/metacpan-k8s#55]
After https://github.com/metacpan/metacpan-k8s/issues/57 is configured and running, update the PersistentVolumeClaim in the `apps/grep` configuration to point to the rook filesystem for it's storage. This will allow the grep containers to start on any node and still have access to storage.

**Comment by ranguard** [comment]
This was covered in https://github.com/metacpan/metacpan-k8s/commit/7bcfbc73cfe04fac25afd8e9176419f7a6d4ee13
