### ISSUE TITLE
Storage setup

### ISSUE THREAD

**Issue by ranguard** [metacpan/metacpan-k8s#57]
- [ ] `/mnt/rook_volume` Resilient and replicated across all 3 nodes automatically and available to all containers
    - 3 [Volumes](https://docs.hetzner.com/cloud/volumes/overview/), one per node
    - Setup rook/ceph https://github.com/DO-Solutions/doks-rook-ceph
    - E.g. BackPan data
    - Use [metacpan-servers terraform](https://github.com/metacpan/metacpan-servers/)
- [ ] `/mnt/tmp_storage_box` single shared, but not so resilient
    - [Storage box](https://www.hetzner.com/storage/storage-box/)
    - Setup automated snapshots
    - E.g. Grep.metacpan, unzipped packages for metacpan-api
    - Mount using sshfs or [rclone](https://docs.hetzner.com/robot/storage-box/access/access-ssh-rsync-borg/#rclone)
        - Note max 10 connections, but think we are only using one per node so ok?
- [ ] `/mnt/independent_volume` volume that is unique per node
    - 3 [Volumes](https://docs.hetzner.com/cloud/volumes/overview/), one per node
    - e.g. Postgres/other services which handles their own replication

### Off site backup
- Postgres, currently only deal with the Minion queue so not needed
- ElasticSearch, will be handled by ES
- BackPan, We currently run the rrr-watcher (which maintains our backpan) on all bm/lw servers so that's covered for now, but we might want something else later

**Comment by ssoriche** [comment]
Containers accessing storage box should mount the  volume directly. Preferable that they write directly to the storage using an object store API than a mount. 

Serving from storage box should be https directly from the browser. Need to research how this gets configured and update API to serve new location.

**Comment by ranguard** [comment]
> Containers accessing storage box should mount the volume directly. Preferable that they write directly to the storage using an object store API than a mount.
> 
> Serving from storage box should be https directly from the browser. Need to research how this gets configured and update API to serve new location.

https://docs.hetzner.com/robot/storage-box/general#general-information "There is a 10-connection limit on each Storage Box account. - I don't know what that will mean in practice!

Maybe we should be looking at [Storage-share](https://www.hetzner.com/storage/storage-share/) - [comparison table](https://docs.hetzner.com/robot/storage-box/faq/storage-box-vs-storage-share) - but that only supports webdav, though maybe that's enough and a better option?

**Comment by ranguard** [comment]
We have setup https://github.com/metacpan/metacpan-k8s/tree/main/platform/hetzner-csi which we hope will allow auto provisioning of volumes in hetzner

**Comment by ranguard** [comment]
[Storage box](https://www.hetzner.com/storage/storage-box/) ruled out - the 10 connections seems to be similtanious not just host

**Comment by ranguard** [comment]
Ended up using DO volumes and https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner.

Discussed using something like S3 for the cpancover project (who want to us our k8s). Then we _just_ have the CPAN backpan and the tmp for API to think about, but can work those out as part of working on those features
