### ISSUE TITLE
Postgres setup

### ISSUE THREAD

**Issue by ranguard** [metacpan/metacpan-k8s#59]
https://cloudnative-pg.io/

See https://github.com/metacpan/metacpan-k8s/discussions/51

TODO:

Should we think about saving backups somewhere? - currently only for Minon but eventually might be more important stuff?

**Comment by ssoriche** [comment]
We can back up to storage box. There is 3 copies of the data in Postgres and we can snapshot to storage box on a regular cadence.

**Comment by ranguard** [comment]
https://cloudnative-pg.io/ can also backup to S3
