### ISSUE TITLE
Add startup and liveness probes to metacpan-web

### ISSUE THREAD

**Issue by ssoriche** [metacpan/metacpan-k8s#84]
Startup and liveness probes tell kubernetes when the pod is ready to receive traffic and whether or not it is still healthy to receive traffic.

If there is an endpoint that's used by Fastly to determine whether the web application is able to receive traffic, it should be used by kubernetes too.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by ranguard** [comment]
Now using DO's load balancer and pointing Fastly at that directly
